name: IoTree MQTT Auto Discovery
slug: iotree_mqtt_auto
version: "2.0.0"
description: Dynamische MQTT-Discovery mit Konfig-UI
startup: services
boot: auto
host_network: true
panel_icon: mdi:access-point-network
panel_title: IoTree MQTT
options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
schema:
  mqtt_host: str
  mqtt_port: int
