name: IoTree MQTT Auto Discovery
slug: iotree_mqtt_auto
version: "0.0.3"
description: Dynamische MQTT-Discovery mit Konfig-UI
startup: services
boot: auto
host_network: true

arch:
  - amd64
  - armv7
  - armhf
  - aarch64

panel_icon: mdi:access-point-network
panel_title: IoTree MQTT

options:
  mqtt_host: mqtt.mdcc.iotree.de
  mqtt_port: 8883
  mqtt_username: "iotree-mdcc"
  mqtt_password: ""
  mqtt_topic: "physec/iotree-+/iot-platform/+/sensor/+/+"

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  mqtt_topic: str



